name: Docker Build

on: [push]

jobs:
  build:
    runs-on: ubuntu:latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t quiz-app .
      - name: Test Docker image
        run: docker run quiz-app sh -c "echo 'Docker image is working!'"